use alloc::vec;
use alloc::vec::Vec;

use crate::Error;

/// Signature of the `.tlm` file generated by `tools/export.py`.
pub const MAGIC: &[u8; 4] = b"TLM1";

/// Model hyperparameters (same fields as llama2.c).
#[derive(Debug, Clone, Copy)]
pub struct Config {
    pub dim: usize,
    pub hidden_dim: usize,
    pub n_layers: usize,
    pub n_heads: usize,
    pub n_kv_heads: usize,
    pub vocab_size: usize,
    pub seq_len: usize,
}

impl Config {
    pub fn head_size(&self) -> usize {
        self.dim / self.n_heads
    }
    pub fn kv_dim(&self) -> usize {
        self.dim * self.n_kv_heads / self.n_heads
    }
}

/// `rows x cols` int8 matrix with one f32 scale per row.
/// `data` points straight into the original blob (flash on the S3); only the scales
/// are copied to the heap, because the blob may not be 4-byte aligned.
pub struct QMatrix<'a> {
    pub rows: usize,
    pub cols: usize,
    pub data: &'a [i8],
    pub scales: Vec<f32>,
}

pub struct Layer<'a> {
    pub rms_att: Vec<f32>,
    pub wq: QMatrix<'a>,
    pub wk: QMatrix<'a>,
    pub wv: QMatrix<'a>,
    pub wo: QMatrix<'a>,
    pub rms_ffn: Vec<f32>,
    pub w1: QMatrix<'a>,
    pub w2: QMatrix<'a>,
    pub w3: QMatrix<'a>,
}

pub struct Model<'a> {
    pub config: Config,
    pub embedding: QMatrix<'a>,
    pub layers: Vec<Layer<'a>>,
    pub rms_final: Vec<f32>,
    /// `None` when the classifier shares weights with the embedding.
    pub wcls: Option<QMatrix<'a>>,
}

// ---------------------------------------------------------------------------
// Sequential blob reader
// ---------------------------------------------------------------------------

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn take(&mut self, n: usize) -> Result<&'a [u8], Error> {
        let end = self.pos.checked_add(n).ok_or(Error::Truncated)?;
        if end > self.buf.len() {
            return Err(Error::Truncated);
        }
        let s = &self.buf[self.pos..end];
        self.pos = end;
        Ok(s)
    }

    fn u32(&mut self) -> Result<u32, Error> {
        let b = self.take(4)?;
        Ok(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
    }

    fn f32s(&mut self, n: usize) -> Result<Vec<f32>, Error> {
        let b = self.take(n * 4)?;
        Ok(b.chunks_exact(4)
            .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect())
    }

    fn i8s(&mut self, n: usize) -> Result<&'a [i8], Error> {
        let b = self.take(n)?;
        // u8 and i8 have the same layout; reinterpreting is safe.
        Ok(unsafe { core::slice::from_raw_parts(b.as_ptr() as *const i8, b.len()) })
    }

    fn qmatrix(&mut self, rows: usize, cols: usize) -> Result<QMatrix<'a>, Error> {
        let data = self.i8s(rows * cols)?;
        let scales = self.f32s(rows)?;
        Ok(QMatrix { rows, cols, data, scales })
    }
}

impl<'a> Model<'a> {
    /// Parses the `.tlm` file. Zero-copy for the int8 weights.
    pub fn from_bytes(buf: &'a [u8]) -> Result<Self, Error> {
        let mut r = Reader { buf, pos: 0 };
        if r.take(4)? != MAGIC {
            return Err(Error::BadMagic);
        }
        let config = Config {
            dim: r.u32()? as usize,
            hidden_dim: r.u32()? as usize,
            n_layers: r.u32()? as usize,
            n_heads: r.u32()? as usize,
            n_kv_heads: r.u32()? as usize,
            vocab_size: r.u32()? as usize,
            seq_len: r.u32()? as usize,
        };
        let flags = r.u32()?;
        let shared_cls = flags & 1 != 0;

        if config.dim == 0 || config.n_heads == 0 || config.dim % config.n_heads != 0 {
            return Err(Error::BadConfig);
        }

        let c = &config;
        let kv = c.kv_dim();

        let embedding = r.qmatrix(c.vocab_size, c.dim)?;
        let mut layers = Vec::with_capacity(c.n_layers);
        for _ in 0..c.n_layers {
            layers.push(Layer {
                rms_att: r.f32s(c.dim)?,
                wq: r.qmatrix(c.dim, c.dim)?,
                wk: r.qmatrix(kv, c.dim)?,
                wv: r.qmatrix(kv, c.dim)?,
                wo: r.qmatrix(c.dim, c.dim)?,
                rms_ffn: r.f32s(c.dim)?,
                w1: r.qmatrix(c.hidden_dim, c.dim)?,
                w2: r.qmatrix(c.dim, c.hidden_dim)?,
                w3: r.qmatrix(c.hidden_dim, c.dim)?,
            });
        }
        let rms_final = r.f32s(c.dim)?;
        let wcls = if shared_cls {
            None
        } else {
            Some(r.qmatrix(c.vocab_size, c.dim)?)
        };

        Ok(Model { config, embedding, layers, rms_final, wcls })
    }
}

// ---------------------------------------------------------------------------
// Runtime state (activations + KV cache)
// ---------------------------------------------------------------------------

/// Mutable buffers for one generation. On the S3, allocate them with the PSRAM allocator.
pub struct State {
    pub max_seq: usize,
    x: Vec<f32>,
    xb: Vec<f32>,
    xb2: Vec<f32>,
    hb: Vec<f32>,
    hb2: Vec<f32>,
    q: Vec<f32>,
    att: Vec<f32>,
    logits: Vec<f32>,
    key_cache: Vec<f32>,
    value_cache: Vec<f32>,
    xq: Vec<i8>,
}

impl State {
    /// `max_seq` limits the KV cache (it can be smaller than `config.seq_len`
    /// to fit in SRAM with small models).
    pub fn new(c: &Config, max_seq: usize) -> Self {
        let max_seq = max_seq.min(c.seq_len).max(1);
        let kv = c.kv_dim();
        State {
            max_seq,
            x: vec![0.0; c.dim],
            xb: vec![0.0; c.dim],
            xb2: vec![0.0; c.dim],
            hb: vec![0.0; c.hidden_dim],
            hb2: vec![0.0; c.hidden_dim],
            q: vec![0.0; c.dim],
            att: vec![0.0; c.n_heads * max_seq],
            logits: vec![0.0; c.vocab_size],
            key_cache: vec![0.0; c.n_layers * max_seq * kv],
            value_cache: vec![0.0; c.n_layers * max_seq * kv],
            xq: vec![0; c.dim.max(c.hidden_dim)],
        }
    }

    /// Approximate number of heap bytes this state uses.
    pub fn heap_bytes(&self) -> usize {
        4 * (self.x.len()
            + self.xb.len()
            + self.xb2.len()
            + self.hb.len()
            + self.hb2.len()
            + self.q.len()
            + self.att.len()
            + self.logits.len()
            + self.key_cache.len()
            + self.value_cache.len())
            + self.xq.len()
    }
}

// ---------------------------------------------------------------------------
// Kernels
// ---------------------------------------------------------------------------

/// Quantizes an f32 vector to symmetric int8; returns the scale.
#[inline]
fn quantize(x: &[f32], out: &mut [i8]) -> f32 {
    let mut max = 0.0f32;
    for &v in x {
        let a = if v < 0.0 { -v } else { v };
        if a > max {
            max = a;
        }
    }
    if max == 0.0 {
        for o in out.iter_mut() {
            *o = 0;
        }
        return 1.0;
    }
    let scale = max / 127.0;
    let inv = 1.0 / scale;
    for (o, &v) in out.iter_mut().zip(x) {
        let q = v * inv;
        // round to the nearest integer
        let q = if q >= 0.0 { q + 0.5 } else { q - 0.5 };
        *o = (q as i32).clamp(-127, 127) as i8;
    }
    scale
}

/// out[i] = scale_x * scale_w[i] * sum_j w[i][j] * xq[j]
///
/// This is the hot loop. This is where SIMD/ESP-NN via FFI comes in later.
#[inline]
fn matmul(out: &mut [f32], w: &QMatrix, xq: &[i8], xscale: f32) {
    let n = w.cols;
    debug_assert_eq!(out.len(), w.rows);
    debug_assert!(xq.len() >= n);
    let xq = &xq[..n];
    for (i, o) in out.iter_mut().enumerate() {
        let row = &w.data[i * n..(i + 1) * n];
        let mut acc: i32 = 0;
        // chunks of 4 help the compiler unroll
        let mut rc = row.chunks_exact(4);
        let mut xc = xq.chunks_exact(4);
        for (r, x) in (&mut rc).zip(&mut xc) {
            acc += r[0] as i32 * x[0] as i32
                + r[1] as i32 * x[1] as i32
                + r[2] as i32 * x[2] as i32
                + r[3] as i32 * x[3] as i32;
        }
        for (r, x) in rc.remainder().iter().zip(xc.remainder()) {
            acc += *r as i32 * *x as i32;
        }
        *o = acc as f32 * xscale * w.scales[i];
    }
}

#[inline]
fn rmsnorm(out: &mut [f32], x: &[f32], weight: &[f32]) {
    let mut ss = 0.0f32;
    for &v in x {
        ss += v * v;
    }
    ss = ss / x.len() as f32 + 1e-5;
    let inv = 1.0 / libm::sqrtf(ss);
    for ((o, &v), &w) in out.iter_mut().zip(x).zip(weight) {
        *o = w * (v * inv);
    }
}

#[inline]
fn softmax(x: &mut [f32]) {
    let mut max = x[0];
    for &v in x.iter() {
        if v > max {
            max = v;
        }
    }
    let mut sum = 0.0f32;
    for v in x.iter_mut() {
        *v = libm::expf(*v - max);
        sum += *v;
    }
    let inv = 1.0 / sum;
    for v in x.iter_mut() {
        *v *= inv;
    }
}

#[inline]
fn dequant_row(out: &mut [f32], m: &QMatrix, row: usize) {
    let n = m.cols;
    let s = m.scales[row];
    for (o, &v) in out.iter_mut().zip(&m.data[row * n..(row + 1) * n]) {
        *o = v as f32 * s;
    }
}

// ---------------------------------------------------------------------------
// Forward
// ---------------------------------------------------------------------------

impl<'a> Model<'a> {
    /// Processes one token at position `pos` and returns the logits.
    /// `pos` must be less than `state.max_seq`.
    pub fn forward<'s>(&self, s: &'s mut State, token: usize, pos: usize) -> &'s [f32] {
        let c = &self.config;
        let dim = c.dim;
        let kv_dim = c.kv_dim();
        let kv_mul = c.n_heads / c.n_kv_heads;
        let hs = c.head_size();
        let max_seq = s.max_seq;
        debug_assert!(pos < max_seq);

        // token embedding
        dequant_row(&mut s.x, &self.embedding, token);

        for (l, layer) in self.layers.iter().enumerate() {
            // --- attention ---
            rmsnorm(&mut s.xb, &s.x, &layer.rms_att);
            let xs = quantize(&s.xb, &mut s.xq[..dim]);

            let loff = l * max_seq * kv_dim;
            let kslot = loff + pos * kv_dim;
            matmul(&mut s.q, &layer.wq, &s.xq, xs);
            matmul(&mut s.key_cache[kslot..kslot + kv_dim], &layer.wk, &s.xq, xs);
            matmul(&mut s.value_cache[kslot..kslot + kv_dim], &layer.wv, &s.xq, xs);

            // RoPE on q and k (computed on the fly)
            {
                let k = &mut s.key_cache[kslot..kslot + kv_dim];
                let mut i = 0;
                while i < dim {
                    let head_dim = (i % hs) as f32;
                    let freq = 1.0 / libm::powf(10000.0, head_dim / hs as f32);
                    let val = pos as f32 * freq;
                    let (fcr, fci) = (libm::cosf(val), libm::sinf(val));
                    // q always; k only within kv_dim
                    let (q0, q1) = (s.q[i], s.q[i + 1]);
                    s.q[i] = q0 * fcr - q1 * fci;
                    s.q[i + 1] = q0 * fci + q1 * fcr;
                    if i < kv_dim {
                        let (k0, k1) = (k[i], k[i + 1]);
                        k[i] = k0 * fcr - k1 * fci;
                        k[i + 1] = k0 * fci + k1 * fcr;
                    }
                    i += 2;
                }
            }

            // multihead attention
            let inv_sqrt = 1.0 / libm::sqrtf(hs as f32);
            for h in 0..c.n_heads {
                let q = &s.q[h * hs..(h + 1) * hs];
                let att = &mut s.att[h * max_seq..h * max_seq + pos + 1];
                let kvh = (h / kv_mul) * hs;
                for (t, a) in att.iter_mut().enumerate() {
                    let koff = loff + t * kv_dim + kvh;
                    let k = &s.key_cache[koff..koff + hs];
                    let mut score = 0.0f32;
                    for (qi, ki) in q.iter().zip(k) {
                        score += qi * ki;
                    }
                    *a = score * inv_sqrt;
                }
                softmax(att);
                let xbh = &mut s.xb[h * hs..(h + 1) * hs];
                for v in xbh.iter_mut() {
                    *v = 0.0;
                }
                for (t, &a) in att.iter().enumerate() {
                    let voff = loff + t * kv_dim + kvh;
                    let v = &s.value_cache[voff..voff + hs];
                    for (o, vi) in xbh.iter_mut().zip(v) {
                        *o += a * vi;
                    }
                }
            }

            // output projection + residual
            let xs = quantize(&s.xb, &mut s.xq[..dim]);
            matmul(&mut s.xb2, &layer.wo, &s.xq, xs);
            for (x, &d) in s.x.iter_mut().zip(&s.xb2) {
                *x += d;
            }

            // --- FFN (SwiGLU) ---
            rmsnorm(&mut s.xb, &s.x, &layer.rms_ffn);
            let xs = quantize(&s.xb, &mut s.xq[..dim]);
            matmul(&mut s.hb, &layer.w1, &s.xq, xs);
            matmul(&mut s.hb2, &layer.w3, &s.xq, xs);
            for (h, &g) in s.hb.iter_mut().zip(&s.hb2) {
                let silu = *h * (1.0 / (1.0 + libm::expf(-*h)));
                *h = silu * g;
            }
            let hs_ = quantize(&s.hb, &mut s.xq[..c.hidden_dim]);
            matmul(&mut s.xb, &layer.w2, &s.xq, hs_);
            for (x, &d) in s.x.iter_mut().zip(&s.xb) {
                *x += d;
            }
        }

        // final norm + classifier
        rmsnorm(&mut s.xb, &s.x, &self.rms_final);
        let xs = quantize(&s.xb, &mut s.xq[..dim]);
        let cls = self.wcls.as_ref().unwrap_or(&self.embedding);
        matmul(&mut s.logits, cls, &s.xq, xs);
        &s.logits
    }
}
